### ISSUE TITLE
Yarn error loading plugin

### ISSUE THREAD

**Issue by flavioespinoza** [michaelversus/insomnia-plugin-codegen#1]
# Overview
Attempt to install plugin throws Yarn error:
- from `preferences/plugin` using npm package-name
- from https://insomnia.rest/plugins/insomnia-plugin-codegen/

## System
- ProductName:	Mac OS X
- ProductVersion:	10.14.6
- BuildVersion:	18G3020

## Insomnia
- v7.1.1

## Error
Screenshot:
<img width="931" alt="Screen Shot 2020-04-07 at 10 22 31 AM" src="https://user-images.githubusercontent.com/2214913/78694854-84791780-78ba-11ea-9c69-15e069d2421b.png">

**Comment by michaelversus** [comment]
@flavioespinoza Thanks for this one!
Try installing again now (version 1.1.4 resolves this issue)
