### ISSUE TITLE
Have you considered contributing this to httpsnippet itself?

### ISSUE THREAD

**Issue by dimitropoulos** [michaelversus/insomnia-plugin-codegen#4]
Hi!

We've recently been putting quite a bit of effort back into httpsnippet, and I'd be curious what you think of contributing this to httpsnippet (in general).

lemme know :)

**Comment by michaelversus** [comment]
@dimitropoulos sure. I don't have time to contribute for this tool unfortunately so if you think it can help httpsnippet is fine by me.

**Comment by michaelversus** [comment]
@dimitropoulos The plugin has a workaround that uses a fork of the httpsnippet library because httpsnippet didn't support somehow injecting custom templates @ a certain path when i was building this. Can you provide some guidelines on how we could achieve this?

**Comment by dimitropoulos** [comment]
sorry: I really wish I could help more but I don't work for Kong anymore and tangentially I'm not sure how bright the future is like for insomnia plugins and how "worth it" this would be at this point.
